// <auto-generated />
using System;
using Atlas.Web.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Atlas.Web.Core.Migrations
{
    [DbContext(typeof(MDContext))]
    [Migration("20210201171709_AddedAnnouncements")]
    partial class AddedAnnouncements
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Atlas.Web.Core.Models.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Long")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.OrganizationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("OrganizationGroups");
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UmbracoMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("SiteId");

                    b.ToTable("OrganizationMembers");
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SiteOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SiteOwnerId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BandModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsurancePolicyNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicensPlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPax")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrimaryDriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResponsibleForMaintenanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PrimaryDriverId");

                    b.HasIndex("ResponsibleForMaintenanceId");

                    b.HasIndex("SiteId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("OrganizationGroupOrganizationMember", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MembersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupsId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("OrganizationGroupOrganizationMember");
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.OrganizationGroup", b =>
                {
                    b.HasOne("Atlas.Web.Core.Models.Announcement", null)
                        .WithMany("SelectedGroups")
                        .HasForeignKey("AnnouncementId");
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.OrganizationMember", b =>
                {
                    b.HasOne("Atlas.Web.Core.Models.Announcement", null)
                        .WithMany("SelectedMembers")
                        .HasForeignKey("AnnouncementId");

                    b.HasOne("Atlas.Web.Core.Models.Site", null)
                        .WithMany("SiteStaff")
                        .HasForeignKey("SiteId");
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.Site", b =>
                {
                    b.HasOne("Atlas.Web.Core.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("Atlas.Web.Core.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.HasOne("Atlas.Web.Core.Models.OrganizationMember", "SiteOwner")
                        .WithMany()
                        .HasForeignKey("SiteOwnerId");

                    b.Navigation("Location");

                    b.Navigation("Organization");

                    b.Navigation("SiteOwner");
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.Vehicle", b =>
                {
                    b.HasOne("Atlas.Web.Core.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.HasOne("Atlas.Web.Core.Models.OrganizationMember", "PrimaryDriver")
                        .WithMany()
                        .HasForeignKey("PrimaryDriverId");

                    b.HasOne("Atlas.Web.Core.Models.OrganizationMember", "ResponsibleForMaintenance")
                        .WithMany()
                        .HasForeignKey("ResponsibleForMaintenanceId");

                    b.HasOne("Atlas.Web.Core.Models.Site", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("SiteId");

                    b.Navigation("Organization");

                    b.Navigation("PrimaryDriver");

                    b.Navigation("ResponsibleForMaintenance");
                });

            modelBuilder.Entity("OrganizationGroupOrganizationMember", b =>
                {
                    b.HasOne("Atlas.Web.Core.Models.OrganizationGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.Web.Core.Models.OrganizationMember", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.Announcement", b =>
                {
                    b.Navigation("SelectedGroups");

                    b.Navigation("SelectedMembers");
                });

            modelBuilder.Entity("Atlas.Web.Core.Models.Site", b =>
                {
                    b.Navigation("SiteStaff");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
